// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vljkbatorrdukqqthhrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsamtiYXRvcnJkdWtxcXRoaHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTQwMTEsImV4cCI6MjA2MDUzMDAxMX0.NXIry5CJHZr94S7PjqkDtSOBQZ-fMn1DwiRkS4A_A5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);